[project]
name = "cefi-driver"
authors = []
description = "Decentralized asset management protocol for digital asset tokenization and trading"
telemetry = false
requirements = []
[contracts.asset-driver]
path = "contracts/asset-driver.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
